### ISSUE TITLE
 [Nhóm #6] Lỗi phi chức năng - thẻ iframe không có title cho screen reader - https://gec.edu.vn/

### ISSUE THREAD

**Issue by 31211027604** [UEHMonQAQC/23_901#206]
a.Web browser: Chrome
b. Các bước phát hiện lỗi:
i. Truy cập trang https://gec.edu.vn/
ii. Mở dev tools (CTRL+Inspect), chạy lighthouse (tick chọnDevice: desktop)
![image](https://github.com/UEHMonQAQC/23_901/assets/142002482/8b1b5841-1152-4e0a-9996-1c5b649b3c64)
iii. Kéo xuống mục NAMES AND LABELS
c. Kết quả thực tế: thẻ iframe không có title cho screen reader
![image](https://github.com/UEHMonQAQC/23_901/assets/142002482/53f601fb-2add-43db-97de-b6c30c07de3d)
d. Kết quả mong đợi: thẻ iframe có title

**Comment by DaThuztdontknowcode** [comment]
Không tìm thấy lỗi đó
![Capture](https://github.com/UEHMonQAQC/23_901/assets/117471031/34fbd8b3-c187-49b0-8ab0-1bfb5db497ef)

**Comment by 31211027604** [comment]
Nhóm đặt nhầm tittle và nội dung của lỗi #203, nhóm đã sửa lại

**Comment by DaThuztdontknowcode** [comment]
QA xác nhận lại đây không đủ căn cứ để xác định lỗi , nên từ chối lỗi này
